services:
  tactical-ops-aot-34-docker:
    image: sin7ek/tactical-ops-aot-34-docker:latest
    container_name: tactical-ops-aot-34-docker
    restart: unless-stopped

    environment:
      SERVER_ZIP_URL: "https://mirror.tactical-ops.eu/anticheat-server/servers/TO340Server-v469d-TOST4240-Nexgen113-ACE12e.zip"
      MAP: "TO-Blister"
      GAME: "s_SWAT.s_SWATGame"
      SERVER_INI: "TacticalOps-Server.ini"
      EXTRA_PARAMS: ""
      SYSTEM_DIR: "/server/System"

      ENABLE_WEBADMIN: "true"
      WEBADMIN_PORT: "5080"
      WEBADMIN_USER: "admin"
      WEBADMIN_PASSWORD: "change-me"

    volumes:
      - ./server:/server:rw

    ports:
      - "7777-7779:7777-7779/udp"
      - "6665:6665/udp"
      - "5080:5080/tcp"

    # Optional Unraid labels
    # labels:
    #   net.unraid.docker.webui: "http://[IP]:[PORT:5080]/"
    #   net.unraid.docker.icon: "https://cdn2.steamgriddb.com/logo_thumb/7e2f21ec8c69203309c420fdf06d4012.png"
